# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'azrepos-azrg-connection'
      subscriptionId: '830248f2-52b1-4955-8d2b-f8e3f22a2bbb'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'myRG'
      location: 'Canada Central'
      templateLocation: 'URL of the file'
      csmFileLink: 'https://raw.githubusercontent.com/MahindraManoj/arm-templates/master/WinServerVmDeploy/azuredeploy.json'
      csmParametersFileLink: 'https://raw.githubusercontent.com/MahindraManoj/arm-templates/master/WinServerVmDeploy/azuredeploy.parameters.json'
      deploymentMode: 'Incremental'
